version: '2'
services:
  dna:
    image: dna
    ports:
      - 80:80
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: library/mongo:3.4.10
    ports:
      - 27017:27017
    volumes:
    - './dev/data/db:/data/db'
    links:
      - mongo
    depends_on:
      - mongo